plugins {
  id 'application'
  id 'java-test-fixtures'
}

dependencies {
  implementation project(':xanadu-core')
  implementation libs.jline
  runtimeOnly libs.h2
  runtimeOnly project(':xanadu-jdbc')
  runtimeOnly project(':xanadu-gemini')
  runtimeOnly project(':xanadu-chatgpt')
  runtimeOnly project(':xanadu-claude')
  testImplementation libs.junit.jupiter
  testImplementation testFixtures(project(':xanadu-core'))
}

test {
  useJUnitPlatform()
}

application {
  // Launch SQLLine as the CLI entrypoint
  mainClass = 'codes.ry.xanadu.Main'
}
